blank_issues_enabled: true
contact_links:
  - name: Request feedback on a specification proposal idea
    about: For early-stage informal specification proposals
    url: https://github.com/harp-tech/protocol/discussions/new?category=open-ended
